"""empty message

Revision ID: 1f3d15f918cd
Revises: 99532c06dab6
Create Date: 2023-05-10 08:47:21.098196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3d15f918cd'
down_revision = '99532c06dab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
